### PR TITLE
adding 5M & 10M (10 query) scripts and 5M benchmark csv

### PR DESCRIPTION
**Pull request by jtbenson116**
### What's being changed:
adding 5M & 10M (10 query) scripts and 5M benchmark csv

### CODE REVIEW

**Review by sourcesync — CHANGES_REQUESTED** [review]
Can you remove "benchmarks_deep10M.sh" from this pull request/the local branch?  Let's save that one for a separate 10M pull request.  Note that you probably want to copy to file somewhere outside the repo, but you need to remove it from the branch by typing:  "git rm \<file path\>"

**Review by sourcesync — CHANGES_REQUESTED** [review]
Can you also change the analysis notebook to incorporate your new benchmarks?  Thanks.

**Review by sourcesync — CHANGES_REQUESTED** [review]
Looks good!  Can you please add a query_size=100 and query_size=1000 to your 5M experiments and update the notebook, graphic accordingly?  Thanks.

**Comment by jtbenson116** [comment]
Yes that would be great.

**Comment by sourcesync** [comment]
@jtbenson116 Thanks for closing this PR per my request.  I suggest maybe waiting a few days before completely deleting this branch locally and remotely.

**Pull request closed without merging**
